version: '3.9'

x-db:
  database_username_root: &db_username_root "admin"
  database_password_root: &db_password_root "admin"
  database_db_root: &db_name_root "admin"

services:
  clickhouse:
        image: yandex/clickhouse-server
        hostname: clickhouse
        container_name: clickhouse
        ports:
            - 9001:9000
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
  mongodb:
    image: mongo:latest
    container_name: mongo 
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: *db_username_root
      MONGO_INITDB_ROOT_PASSWORD: *db_password_root
      MONGO_INITDB_DATABASE: *db_name_root
    volumes:
      - ./docker/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - "27017:27017"
    networks:
      - booking
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongo-data:

networks:
  booking:
    driver: bridge